version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts
      - image: 'circleci/python:2.7'

    working_directory: ~/repo
        
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
      # run tests!
      - run: yarn test
      - run: yarn build
      - aws-s3/sync:
          from: public
          to: 's3://kimlog-content'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          overwrite: true
      
